### ISSUE TITLE
Обновился используемый пакет, в котором убрали поддержку старого функционала

### ISSUE THREAD

**Issue by huxuxuya** [TheDemonCat/onec-full#8]
Вышел новый релиз https://github.com/v8platform/oneget, в котором: 

> #Так больше не работает:
> oneget \
> --user $ONEC_USERNAME \
>     --pwd $ONEC_PASSWORD \
>     --path /tmp/dist/ \
>     --nicks platform83 \
>     --version-filter 8.3.16.1876 \
>     --distrib-filter 'deb64.tar.gz$'

но oneget в докер файле юзает такие аргументы

**Comment by thedemoncat** [comment]
В принципе, в образе была указана точная версии oneget, по этому этой ошибки тут не было.
Но образ переделан на поддержку версии 8.3.20 и выше.
